### ISSUE TITLE
SSL Handshake WRAP produced 0 bytes.

### ISSUE THREAD

**Issue by torkjel** [http4s/blaze#258]
This appears to be similar to https://github.com/http4s/http4s/issues/2192. 

We're running a http4s client (v0.20.0-M4) on Google's Dataproc service (Dataproc image version 1.2.59-deb9), trying to connect to a Vault service (https://www.vaultproject.io/), but consistently getting the error below. 

I have a workaround at https://github.com/torkjel/blaze/pull/1, but I'm not sure about the general soundness of it. 

`Caused by: javax.net.ssl.SSLException: SSL Handshake WRAP produced 0 bytes: Status = OK HandshakeStatus = FINISHED
bytesConsumed = 0 bytesProduced = 0
	at org.http4s.blaze.pipeline.stages.SSLStage.sslHandshakeLoop$1(SSLStage.scala:189)
	at org.http4s.blaze.pipeline.stages.SSLStage.org$http4s$blaze$pipeline$stages$SSLStage$$sslHandshake(SSLStage.scala:212)
	at org.http4s.blaze.pipeline.stages.SSLStage$$anonfun$sslHandshakeLoop$1$1.apply(SSLStage.scala:168)
	at org.http4s.blaze.pipeline.stages.SSLStage$$anonfun$sslHandshakeLoop$1$1.apply(SSLStage.scala:166)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at org.http4s.blaze.util.SerialExecutionContext$$anon$1.act(SerialExecutionContext.scala:22)
	at org.http4s.blaze.util.SerialExecutionContext$$anon$1.act(SerialExecutionContext.scala:21)
	at org.http4s.blaze.util.Actor$RecycleableRunnable.go$1(Actor.scala:57)
	at org.http4s.blaze.util.Actor$RecycleableRunnable.run(Actor.scala:72)
	at org.http4s.blaze.util.Execution$$anon$3.execute(Execution.scala:66)
	at org.http4s.blaze.util.Actor.$bang(Actor.scala:45)
	at org.http4s.blaze.util.SerialExecutionContext.execute(SerialExecutionContext.scala:28)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Promise$class.success(Promise.scala:86)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:153)
	at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$2.completed(ByteBufferHead.scala:90)
	at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$2.completed(ByteBufferHead.scala:73)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) `

**Comment by torkjel** [comment]
Trace log when running with pr #260 applied on offending system:
```
13:04:39.532 [scala-execution-context-global-15] DEBUG o.h.client.blaze.Http1Connection - Beginning request: POST https://example.com/myservice
13:04:39.532 [Thread-6] TRACE o.h.b.util.ThreadLocalScratchBuffer - Allocating thread local ByteBuffer(16709)
13:04:39.533 [scala-execution-context-global-13] DEBUG o.http4s.blazecore.IdleTimeoutStage - Starting idle timeout stage with timeout of 60000 ms
13:04:39.534 [scala-execution-context-global-15] TRACE o.h.client.blaze.Http1Connection - Using static encoder
13:04:39.615 [Thread-6] TRACE o.h.blaze.pipeline.stages.SSLStage - SSL Handshake Status after wrap: Status = OK HandshakeStatus = NEED_UNWRAP
bytesConsumed = 0 bytesProduced = 105
13:04:39.616 [Thread-6] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: sslHandshake completed in 83334278ns
13:04:39.616 [Thread-6] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: continueWrite completed in 471457ns
13:04:39.616 [Thread-6] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: sslHandshake completed in 81507ns
13:04:39.617 [Thread-2] TRACE o.h.b.util.ThreadLocalScratchBuffer - Allocating thread local ByteBuffer(16709)
13:04:39.617 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - SSL Handshake Status after wrap: Status = OK HandshakeStatus = FINISHED
bytesConsumed = 0 bytesProduced = 0
13:04:39.618 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: sslHandshake completed in 759629ns
13:04:39.619 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - Submitting backed up ops: List(DelayedRead(-1,Future(<not completed>)), DelayedWrite([Ljava.nio.ByteBuffer;@2f15645d,Future(<not completed>)))
13:04:39.620 [Thread-2] DEBUG o.h.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16709 cap=16709]
13:04:39.620 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: doRead completed in 694108ns
13:04:39.626 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: continueWrite completed in 5342441ns
13:04:39.626 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: sslHandshake completed in 8018147ns
13:04:39.626 [Thread-2] DEBUG o.h.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 237 bytesProduced = 208, java.nio.HeapByteBuffer[pos=208 lim=16709 cap=16709]
13:04:39.626 [Thread-2] DEBUG o.h.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16709 cap=16709]
13:04:39.626 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: doRead completed in 335628ns
13:04:39.628 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: continueWrite completed in 1929519ns
13:04:39.628 [Thread-2] DEBUG o.h.blaze.pipeline.stages.SSLStage - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16709 cap=16709]
13:04:39.629 [Thread-2] TRACE o.h.blaze.pipeline.stages.SSLStage - 1536927475: doRead completed in 222878ns
13:04:39.633 [scala-execution-context-global-22] DEBUG o.h.client.blaze.Http1Connection - Resetting org.http4s.client.blaze.Http1Connection after completing request.
13:04:39.633 [scala-execution-context-global-22] DEBUG o.h.b.ResponseHeaderTimeoutStage - Shutting down response header timeout stage
```
