### ISSUE TITLE
Unhelpful UnresolvedAddressException

### ISSUE THREAD

**Issue by tomasherman** [http4s/blaze#373]
Hi,

we are getting this really unhelpful exception when trying to connect to address that does not exist:
```
java.nio.channels.UnresolvedAddressException: null
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:130)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implConnect(UnixAsynchronousSocketChannelImpl.java:305)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.connect(AsynchronousSocketChannelImpl.java:210)
	at org.http4s.blaze.channel.nio2.ClientChannelFactory.connect(ClientChannelFactory.scala:62)
	at org.http4s.client.blaze.Http1Support.buildPipeline(Http1Support.scala:63)
	at org.http4s.client.blaze.Http1Support.$anonfun$makeClient$1(Http1Support.scala:56)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
	at monix.eval.internal.TaskRestartCallback$WithLocals.syncOnSuccess(TaskRestartCallback.scala:176)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
	at monix.eval.internal.TaskCreate$CallbackForCreate.run(TaskCreate.scala:252)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:132)
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:40)
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:57)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
	at monix.execution.schedulers.TracingScheduler$Base.execute(TracingScheduler.scala:53)
	at monix.execution.schedulers.StartAsyncBatchRunnable.run(StartAsyncBatchRunnable.scala:42)
	at monix.execution.schedulers.TracingRunnable.run(TracingRunnable.scala:33)
	at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
	at monix.execution.internal.forkJoin.AdaptedForkJoinTask.exec(AdaptedForkJoinTask.scala:27)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
is there any way to improve it? Are we doing something wrong?

Thanks!

**Comment by rossabaker** [comment]
This is a [Java wart]( https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/nio/ch/Net.java#L149).  The exception type is appropriate, but for whatever reason, this exception doesn't take a message (or better yet, the `SocketAddress`).

We could do one of three things here:
1. Wrap the `UnresolvedAddressException`
2. Extend `UnresolvedAddressException` with something that takes an address argument and overrides the message.  This would have the benefit of not changing any downstream exception handling, though it's unlikely that anything specific exists.
3. Log the socket address and complete the promise with the original exception.  I am not usually a fan of both logging and throwing/wrapping errors.

**Comment by tomasherman** [comment]
If i understand things correctly, this is happening when dns lookup fails, correct? Ideally i would love to know which address failed to resolve. I am ok with either 1 or 2 - i think 1 is cleaner but 2 is more safe if we are worried about making a breaking change

**Comment by tomasherman** [comment]
i would prefer not to log this and modify the exception instead, i think people generally have logging like this turned off and assume that the exceptions will provide enough detail - i know that is the case for us

**Comment by rossabaker** [comment]
On second thought, we can fix this better in http4s itself.  I went with option #1.  PR coming.

**Comment by tomasherman** [comment]
thank you, i think we can close this then
