### ISSUE TITLE
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?

### ISSUE THREAD

**Issue by FreddieSanchez** [http4s/blaze#501]
open JDK 8, Scala `2.12.12`

```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

```
Error while closing SSL Engine 
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?

    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647)
    at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615)
    at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1542)
    at org.http4s.blaze.pipeline.stages.SSLStage.stageShutdown(SSLStage.scala:66)
    at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:85)
    at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:84)
    at org.http4s.blaze.pipeline.stages.SSLStage.closePipeline(SSLStage.scala:47)
    at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:88)
    at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:84)
    at org.http4s.client.blaze.ReadBufferStage.closePipeline(ReadBufferStage.scala:30)
    at org.http4s.blaze.pipeline.Tail.closePipeline(Stages.scala:88)
    at org.http4s.blaze.pipeline.Tail.closePipeline$(Stages.scala:84)
    at org.http4s.client.blaze.Http1Connection.closePipeline(Http1Connection.scala:41)
    at org.http4s.client.blaze.Http1Connection.shutdownWithError(Http1Connection.scala:101)
    at org.http4s.client.blaze.Http1Connection.stageShutdown(Http1Connection.scala:71)
    at org.http4s.client.blaze.Http1Connection.shutdown(Http1Connection.scala:69)
    at org.http4s.client.PoolManager.$anonfun$releaseRecyclable$10(PoolManager.scala:244)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
       ...
```

Some log entries prior to the failure: 
```
2021-02-12 20:52:15.098 [Thread-5] [39mDEBUG[0;39m [36mo.h.b.p.s.SSLStage[0;39m - SSL Read Request Status: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 213 bytesProduced = 157, java.nio.HeapByteBuffer[pos=157 lim=16921 cap=16921] 
2021-02-12 20:52:15.099 [Thread-5] [39mDEBUG[0;39m [36mo.h.b.p.s.SSLStage[0;39m - SSL Read Request Status: Status = OK HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 293 bytesProduced = 240, java.nio.HeapByteBuffer[pos=240 lim=16921 cap=16921] 
2021-02-12 20:52:15.099 [Thread-5] [39mDEBUG[0;39m [36mo.h.b.p.s.SSLStage[0;39m - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921] 
2021-02-12 20:52:15.099 [Thread-5] [39mDEBUG[0;39m [36mo.h.b.p.s.SSLStage[0;39m - SSL Read Request Status: Status = BUFFER_UNDERFLOW HandshakeStatus = NOT_HANDSHAKING
bytesConsumed = 0 bytesProduced = 0, java.nio.HeapByteBuffer[pos=0 lim=16921 cap=16921] 
2021-02-12 20:52:15.099 [pool-3-thread-31] [39mDEBUG[0;39m
```

**Comment by rossabaker** [comment]
This was added in https://github.com/http4s/blaze/pull/305.  We are suppressing SSLException down to DEBUG at that level, because they're somewhat expected and I don't think there's anything we can do about them.  But rereading the javadoc, _maybe_ we can hush it by calling `closeOutbound()` first.
