### ISSUE TITLE
Out-of-memory exceptions

### ISSUE THREAD

**Issue by tindzk** [http4s/blaze#56]
I consistently run into out-of-memory exceptions when I use the HTTP client in parallel for a couple of minutes:

```scala
val batchSize = 50
val batches   = urls.sliding(batchSize, batchSize).toList

def resolveRedirect(url: String, redirects: Int = 5): Task[Option[String]] = ???  // See #55

batches.zipWithIndex.foreach { case (batch, i) =>
  println(s"Batch ${i + 1}/${batches.length}")
  scalaz.concurrent.Task.gatherUnordered(
    batch.map(resolveRedirect(_))
  ).unsafePerformSync
}
```

Apparently, the threads from the previously instantiated clients are not getting cleaned up:

```
2016.12.13 22:07:38:110 [anInnocuousThread] ERROR o.h.b.u.Execution.error:50 - Trampoline EC Exception caught
2016.12.13 22:07:38:110 [anInnocuousThread] ERROR o.h.b.u.Execution.error:51 - java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at org.http4s.client.blaze.ClientTimeoutStage$$anonfun$checkTimeout$1.apply(ClientTimeoutStage.scala:117)
        at org.http4s.client.blaze.ClientTimeoutStage$$anonfun$checkTimeout$1.apply(ClientTimeoutStage.scala:114)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at org.http4s.blaze.util.Execution$$anon$2.execute(Executor.scala:49)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.trySuccess(Promise.scala:94)
        at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:153)
        at org.http4s.blaze.pipeline.stages.SSLStage.org$http4s$blaze$pipeline$stages$SSLStage$$doRead(SSLStage.scala:83)
        at org.http4s.blaze.pipeline.stages.SSLStage$$anonfun$org$http4s$blaze$pipeline$stages$SSLStage$$doRead$1.apply(SSLStage.scala:89)
        at org.http4s.blaze.pipeline.stages.SSLStage$$anonfun$org$http4s$blaze$pipeline$stages$SSLStage$$doRead$1.apply(SSLStage.scala:86)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at org.http4s.blaze.util.Execution$$anon$1.execute(Executor.scala:27)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.trySuccess(Promise.scala:94)
        at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:153)
        at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$3.completed(ByteBufferHead.scala:100)
        at org.http4s.blaze.channel.nio2.ByteBufferHead$$anon$3.completed(ByteBufferHead.scala:87)
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:430)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
        at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
        at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at sun.misc.InnocuousThread.run(InnocuousThread.java:74)
```

**Comment by tindzk** [comment]
The OOM situation does not happen when I explicitly call `shutdownNow`:

```scala
client.expect(url)(text).attempt.map {
  case \/-(dr) => client.shutdownNow(); resolvedUrl
  case -\/(e)  => client.shutdownNow(); None
}
```

But this leads to a lot of warnings regarding potential resource leaks:

```
[...]
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
2016.12.13 23:28:33:668 [Finalizer] WARN  o.h.b.p.Stage.warn:20 - Client was not shut down and could result in a resource leak
[...]
```

**Comment by bryce-anderson** [comment]
Are you making a new `PooledClient` with every request? That appears to be workflow of #55, and is consistent with the behavior you're seeing. The `PooledClient` has a thread pool (of fixed size by default). When you call `client.shutdown`, if the client provided its own thread pool, its shut down. Otherwise, that pool will live until the process dies.

If this needs further discussion, lets continue in the http4s/http4s project.
