### ISSUE TITLE
Blaze Test Is Unreliable

### ISSUE THREAD

**Issue by isomarcte** [http4s/blaze#634]
https://github.com/http4s/http4s/pull/5046/checks?check_run_id=3275323831

```
 ==> X org.http4s.client.blaze.BlazeClient213Suite.behave and not deadlock on failures with parTraverse  50.012s java.util.concurrent.TimeoutException: Future timed out after [50 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:212)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
    at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
    at scala.concurrent.Await$.result(package.scala:124)
    at munit.internal.PlatformCompat$.$anonfun$waitAtMost$1(PlatformCompat.scala:21)
    at scala.util.Try$.apply(Try.scala:210)
    at munit.internal.PlatformCompat$.waitAtMost(PlatformCompat.scala:21)
    at munit.FunSuite.waitForCompletion(FunSuite.scala:51)
    at munit.FunSuite.$anonfun$test$1(FunSuite.scala:37)
    at munit.GenericTest.$anonfun$withBodyMap$1(GenericTest.scala:33)
    at munit.MUnitRunner.$anonfun$runTestBody$1(MUnitRunner.scala:296)
```

If we can't fix this, we might consider disabling it. I'm unsure how much utility a test which is expected to fail often provides.

**Comment by RafalSumislawski** [comment]
I'm closing this one as I think it's been fixed by https://github.com/http4s/http4s/pull/5385
