### ISSUE TITLE
[blaze-client] "Exception: This stage 'IdleTimeoutStage' isn't connected!"

### ISSUE THREAD

**Issue by cquiroz** [http4s/blaze#649]
I'm seeing an exception sometimes when doing client calls:

```
seqexec_web_server java.lang.Exception: This stage 'IdleTimeoutStage' isn't connected!
seqexec_web_server     at org.http4s.blaze.pipeline.Tail._stageDisconnected(Stages.scala:218)
seqexec_web_server     at org.http4s.blaze.pipeline.Tail.channelRead(Stages.scala:90)
seqexec_web_server     at org.http4s.blaze.pipeline.Tail.channelRead$(Stages.scala:85)
seqexec_web_server     at org.http4s.blazecore.IdleTimeoutStage.channelRead(IdleTimeoutStage.scala:12)
seqexec_web_server     at org.http4s.blazecore.IdleTimeoutStage.readRequest(IdleTimeoutStage.scala:35)
seqexec_web_server     at org.http4s.blaze.pipeline.Tail.channelRead(Stages.scala:88)
seqexec_web_server     at org.http4s.blaze.pipeline.Tail.channelRead$(Stages.scala:85)
```

**Comment by xinhuan-myob** [comment]
Is there any update on this issue?

**Comment by Daenyth** [comment]
No. There would be a comment here. I don't expect progress on it since the previous investigation didn't find the cause, and the error doesn't seem to be impacting anything negatively
