### ISSUE TITLE
`org.http4s.blaze.server.BlazeServerSuite.reliably handle multipart requests` fails for Scala3

### ISSUE THREAD

**Issue by danicheg** [http4s/blaze#819]
We have got several firings in different PRs recently. Hard to say why we get this only for Scala 3 🤔 
```
==> X org.http4s.blaze.server.BlazeServerSuite.reliably handle multipart requests  1.229s java.io.IOException: Server returned HTTP response code: 503 for URL: http://127.0.0.1:46529/issue2610
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
    at org.http4s.blaze.server.BlazeServerSuite.postChunkedMultipart$$anonfun$1(BlazeServerSuite.scala:159)
    at blocking @ org.http4s.blaze.server.BlazeServerSuite.get(BlazeServerSuite.scala:115)
    at flatMap @ munit.CatsEffectAssertions.assertIO(CatsEffectAssertions.scala:52)
    at flatMap @ munit.internal.NestingChecks$.checkNestingIO(internal.scala:55)
```
https://github.com/http4s/blaze/actions/runs/5503198443/jobs/10028167871?pr=817#step:8:2151
https://github.com/http4s/blaze/actions/runs/5401204855/jobs/9874011918?pr=816#step:8:2567

**Comment by danicheg** [comment]
And of course, this doesn't reproduce locally 😇

**Comment by danicheg** [comment]
Hmmmm, simply rerunning helped. But anyway, since this has been fired for several PRs at different times, I would mark this test as flaky for CI.
